/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameVentanas;



/**
 *
 * @author Frank
 */
public class JFramePrincipalAsistencia extends javax.swing.JFrame {
       
    /**
     * Creates new form JFramePrincipalAsistencia
     */
    public JFramePrincipalAsistencia() {
        initComponents();
    }
    
    
    
    // Otros métodos y acciones de botones, si es necesario.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTurnoM = new javax.swing.JButton();
        btnTurnoT = new javax.swing.JButton();
        btnTurnoN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bienvenido: Mario Perez");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 30));

        jLabel2.setText("Registro de Asistencia");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnTurnoM.setText("Turno Mañana");
        btnTurnoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoMActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurnoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnTurnoT.setText("Turno Tarde");
        btnTurnoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoTActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurnoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnTurnoN.setText("Turno Noche");
        btnTurnoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoNActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurnoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTurnoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoMActionPerformed
        
        JFrameClaseMañana ventanaclaseM = new JFrameClaseMañana(this);
        ventanaclaseM.setLocationRelativeTo(this);
        ventanaclaseM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTurnoMActionPerformed

    private void btnTurnoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoTActionPerformed

        JFrameClaseTarde ventanaclaseT = new JFrameClaseTarde(this);
        ventanaclaseT.setLocationRelativeTo(this);
        ventanaclaseT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTurnoTActionPerformed

    private void btnTurnoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoNActionPerformed

        JFrameClaseNoche ventanaclaseN = new JFrameClaseNoche(this);
        ventanaclaseN.setLocationRelativeTo(this);
        ventanaclaseN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTurnoNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipalAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTurnoM;
    private javax.swing.JButton btnTurnoN;
    private javax.swing.JButton btnTurnoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
